### ISSUE TITLE
Add support for named variables context

### ISSUE THREAD

**Issue by Natim** [lukewestby/elm-string-interpolate#13]
I was wondering if this lib should add support for context handling?

```elm
import String.Interpolate exposing (interpolateContext)

output : String
output =
  let
     context = Dict.fromList
        [ ("firstname", "Luke")
        , ("lastname"  , "Westby")
        ]
  in
  interpolateContext "My name is {firstname} {lastname}" context

main = show output {- "My name is Luke Westby" -}
```
What do you think?

**Comment by MichaelCombs28** [comment]
I had made a pull request with this functionality like 2 years ago. No feedback, no nothing. I will likely create a separate package in a couple of days.

**Comment by Natim** [comment]
Ok @MichaelCombs28 I would be interested in using it too.

Oh I just noticed https://github.com/lukewestby/elm-string-interpolate/pull/8 :+1:

**Comment by lukewestby** [comment]
Hey folks, I encourage you to fork this package and add the features you want. I'm not working on Elm stuff much anymore.

**Comment by Natim** [comment]
Thank you @lukewestby for your messages about that. @MichaelCombs28 would you like to create the fork or should I?

**Comment by MichaelCombs28** [comment]
I'll fork it now.
